### PR TITLE
Reformat readme paragraphs for better readability

### PR DESCRIPTION
**Pull request by c9s**

### CODE REVIEW

**Comment by kirbyfan64** [comment]
Uh...Markdown ignores line breaks...

**Comment by c9s** [comment]
yes and in console it's harder to read

**Comment by kobalicek** [comment]
I think this is unnecessary, any editor that can do line-wrapping will show it properly, even in terminal.

**Comment by c9s** [comment]
yeah I thought about that yesterday too.. I will close this one.

**Pull request closed without merging**
