### PR TITLE
TypeId::kId fix

### PR DESCRIPTION
**Pull request by blackbird8010**
With these two commits, the project builds (again?) on Mac OS.

For this, I tried to provide overloads for `TypeId::kId` for each fundamental integer type available in standard C++. IMHO, this should be done for **each type** instead of for the fixed width integer types, since when such an overload is called for one of the "normal" integer types (`int`, `long`, etc.), there might be ambiguities or missing overloads. (This is quite a nuisance, because there is a wide range of possible sizes for the integer types.)

The cause of the project failing to build on Mac OS was that `size_t` seems to be a `typedef` for `long`, which might be the same length as `uint64_t`, but which is still a different type, see also [here](http://en.cppreference.com/w/cpp/language/types).

Also, as far as I know, the fixed width integer types as well as the type `long long` are only available since C++11, so I added an `#if` for that. However, just failing to provide overloads for the 64 bit types might or might not be problematic, given that the type `uint64_t` is used extensively elsewhere throughout the project, I simply do not know yet.

I added an assert that requires the `char` types to be exactly 8 bits, since otherwise the way `kId` are set does not make sense.

**Note:** Unfortunately, according to the CI server, a test crashes on Mac OS for the 32 bit builds (both Debug and Release). I'm not yet familiar with this project, and I have not yet been able to track down the cause of the crash.

### CODE REVIEW

**Comment by blackbird8010** [comment]
Alright, I've just noticed the `next` branch, and with those many changes, this pull request will probably be obsolete soon. Never mind :)

**Comment by kobalicek** [comment]
I wanted to save you some work, because I remember I was fixing exactly this issue some time ago (this is why I asked if it compiles on osx:-), but I noticed the next is also failing, will fix this now.

**Comment by blackbird8010** [comment]
Okay, good luck then, and thanks for the awesome project!

**Comment by kobalicek** [comment]
Is this still relevant? A fix has been incorporated to asmjit already, let me know if I should close this.

**Comment by blackbird8010** [comment]
The current head 7c197912fd854870fbcb08d0d1d5b655ffb51582 does compile (including tests) on Mac OS X with Apple LLVM version 7.0.2, so this can be closed.

**Comment by kobalicek** [comment]
Closing, thanks!

**Pull request closed without merging**
